
Main Terraform code file
Create a directory called terraform and navigate to it
mkdir terraform && cd terraform

Create main.tf file and add the resource and output blocks
vi main.tf

variable "age" {
  default = ["20", "21", "22"]  
  type = list(number)
}

Output the age variable and the prefix generated by random_pet
output "age" {
value = var.age
}

output "my_name" {
value = random_pet.my_list.prefix
}

Format the code for readability
terraform fmt

Initialize the Terraform configuration in the current directory
terraform init

Preview the changes to be made
terraform plan

Apply the changes to create the resources
terraform apply

View the state of the resources created
terraform show

Destroy the resources created
terraform destroy
