# main.tf
# This Terraform configuration generates random pet names using the random_pet resource based on age values.
# It outputs both the age variable and the generated pet name prefix.

# Create a random_pet resource with a prefix based on the age variable.
resource "random_pet" "my-list" {
  prefix = var.age[2]
}

# Output the age variable.
output "age" {
  value = var.age[2]
}

# Output the pet name prefix generated by the random_pet resource.
output "my_name" {
  value = random_pet.my-list.prefix
}
