# Define the prefix variable with a default value
variable "prefix" {
  type    = list(string)
  default = ["Vijay", "Kumar", "Biradar"]
}

# Define the random_pet resource
resource "random_pet" "my_list" {
  prefix = var.prefix[0]
}

# Output the prefix variable and the prefix generated by random_pet
output "prefix" {
  value = var.prefix[0]
}

output "my_name" {
  value = random_pet.my_list.prefix
}
